Check for errors from get_dev
We do not want to continue if that fails.

diff --git a/linux/system-config/block-snapshot b/linux/system-config/block-snapshot
--- a/linux/system-config/block-snapshot
+++ b/linux/system-config/block-snapshot
@@ -71,8 +71,7 @@ create_dm_snapshot() {
 
   if [ ! -e "/dev/mapper/$dm_devname" ]; then
     # prepare new snapshot device
-    base_dev=$(get_dev "$base")
-    cow_dev=$(get_dev "$cow")
+    base_dev=$(get_dev "$base") && cow_dev=$(get_dev "$cow") || fatal 'get_dev failed'
     base_sz=$(blockdev --getsz "$base_dev")
     do_or_die dmsetup create "$dm_devname" --table "0 $base_sz snapshot $base_dev $cow_dev P $SNAPSHOT_CHUNKSIZE"
   fi
