Improved file pool block script
The file pool block script really needs to be removed, but this version
is at least easier to understand.

diff --git a/linux/system-config/block-snapshot b/linux/system-config/block-snapshot
--- a/linux/system-config/block-snapshot
+++ b/linux/system-config/block-snapshot
@@ -78,6 +78,10 @@ create_dm_snapshot() {
 
 }
 
+deps () {
+  dmsetup -o blkdevname -- deps "$1" | cut -d: -f2 | sed -e 's#(\([a-z0-9-]\+\))#/dev/\1#g'
+}
+
 create_dm_snapshot_origin() {
   local base_dev base_sz dm_devname base
 
@@ -92,115 +96,113 @@ create_dm_snapshot_origin() {
   fi
 }
 
-t=$(basename "$0")
-t=${t#block-}
+is_unused () {
+  dmsetup -- info "$1" 2>/dev/null|grep -Eq '^Open count: +0$'
+}
+
+in_use () {
+  log info "Device $1 still in use - not removing"
+  release_lock "block"
+  exit 0
+}
+
+unset t
+t=${0#*/}
+case $t in
+  (block-snapshot|block-origin) t=${t#block-};;
+  (*) fatal "Bad script name $t";;
+esac
 
 case "$command" in
   add)
-    case $t in
-      snapshot|origin)
-        p=$(xenstore_read_default "$XENBUS_PATH/params" 'MISSING')
-        if [ "$p" == "MISSING" ]; then
-          fatal "Missing device parameters ($t $XENBUS_PATH/params)"
-        fi
-        echo "$p" > "$HOTPLUG_STORE-params"
-        echo "$t" > "$HOTPLUG_STORE-type"
-        base=${p%%:*}
-        cow=${p#*:}
-        cow2=${p##*:}
-        if [ "$cow" != "$cow2" ]; then
-          cow=${cow%:*}
-        else
-          cow2=""
-        fi
+    p=$(xenstore_read_default "$XENBUS_PATH/params" 'MISSING')
+    if [ "$p" == "MISSING" ]; then
+      fatal "Missing device parameters ($t $XENBUS_PATH/params)"
+    fi
+    echo "$p" > "$HOTPLUG_STORE-params"
+    echo "$t" > "$HOTPLUG_STORE-type"
+    base=${p%%:*}
+    cow=${p#*:}
+    cow2=${p##*:}
+    if [ "$cow" != "$cow2" ]; then
+      cow=${cow%:*}
+    else
+      cow2=""
+    fi
 
-        if [ -L "$base" ]; then
-          base=$(readlink -f "$base") || fatal "$base link does not exist."
-        fi
+    if [ -L "$base" ]; then
+      base=$(readlink -f "$base") || fatal "$base link does not exist."
+    fi
 
-        if [ -L "$cow" ]; then
-          cow=$(readlink -f "$cow") || fatal "$cow link does not exist."
-        fi
+    if [ -L "$cow" ]; then
+      cow=$(readlink -f "$cow") || fatal "$cow link does not exist."
+    fi
 
-        if [ -L "$cow2" ]; then
-          cow2=$(readlink -f "$cow2") || fatal "$cow2 link does not exist."
-        fi
+    if [ -L "$cow2" ]; then
+      cow2=$(readlink -f "$cow2") || fatal "$cow2 link does not exist."
+    fi
 
-        # first ensure that snapshot device exists (to write somewhere changes from snapshot-origin)
-        dm_devname=$(get_dm_snapshot_name "$base" "$cow")
+    # first ensure that snapshot device exists (to write somewhere changes from snapshot-origin)
+    dm_devname=$(get_dm_snapshot_name "$base" "$cow")
 
-        claim_lock "block"
+    claim_lock "block"
 
-        # prepare snapshot device
-        create_dm_snapshot "$dm_devname" "$base" "$cow"
+    # prepare snapshot device
+    create_dm_snapshot "$dm_devname" "$base" "$cow"
 
-        if [ -n "$cow2" ]; then
-          dm_devname_full=$(get_dm_snapshot_name "$base" "$cow" "$cow2")
-          create_dm_snapshot "$dm_devname_full" "/dev/mapper/$dm_devname" "$cow2"
-          dm_devname="$dm_devname_full"
-        fi
+    if [ -n "$cow2" ]; then
+      dm_devname_full=$(get_dm_snapshot_name "$base" "$cow" "$cow2")
+      create_dm_snapshot "$dm_devname_full" "/dev/mapper/$dm_devname" "$cow2"
+      dm_devname="$dm_devname_full"
+    fi
 
-        if [ "$t" == "snapshot" ]; then
-          #that's all for snapshot, store name of prepared device
-          xenstore_write "$XENBUS_PATH/node" "/dev/mapper/$dm_devname"
-          echo "/dev/mapper/$dm_devname" > "$HOTPLUG_STORE-node"
-          write_dev "/dev/mapper/$dm_devname"
-        elif [ "$t" == "origin" ]; then
-          # for origin - prepare snapshot-origin device and store its name
-          dm_devname=origin-$(stat -c '%D:%i' "$base")
-          create_dm_snapshot_origin "$dm_devname" "$base"
-          xenstore_write "$XENBUS_PATH/node" "/dev/mapper/$dm_devname"
-          echo "/dev/mapper/$dm_devname" > "$HOTPLUG_STORE-node"
-          write_dev "/dev/mapper/$dm_devname"
-        fi
+    if [ "$t" == "origin" ]; then
+      # for origin - prepare snapshot-origin device and store its name
+      dm_devname=origin-$(stat -c '%D:%i' "$base")
+      create_dm_snapshot_origin "$dm_devname" "$base"
+    fi
+    xenstore_write "$XENBUS_PATH/node" "/dev/mapper/$dm_devname"
+    echo "/dev/mapper/$dm_devname" > "$HOTPLUG_STORE-node"
+    write_dev "/dev/mapper/$dm_devname"
 
-        release_lock "block"
-        exit 0
-        ;;
-    esac
+    release_lock "block"
+    exit 0
     ;;
   prepare)
     t=$2
-    case $t in
-      snapshot|origin)
-        p=$3
-        base=${p%%:*}
-        cow=${p#*:}
-        cow2=${p##*:}
-        if [ "$cow" != "$cow2" ]; then
-          cow=${cow%:*}
-        else
-          cow2=""
-        fi
+    p=$3
+    base=${p%%:*}
+    cow=${p#*:}
+    cow2=${p##*:}
+    if [ "$cow" != "$cow2" ]; then
+      cow=${cow%:*}
+    else
+      cow2=""
+    fi
 
-        # first ensure that snapshot device exists (to write somewhere changes from snapshot-origin)
-        dm_devname=$(get_dm_snapshot_name "$base" "$cow")
+    # first ensure that snapshot device exists (to write somewhere changes from snapshot-origin)
+    dm_devname=$(get_dm_snapshot_name "$base" "$cow")
 
-        claim_lock "block"
+    claim_lock "block"
 
-        # prepare snapshot device
-        create_dm_snapshot "$dm_devname" "$base" "$cow"
+    # prepare snapshot device
+    create_dm_snapshot "$dm_devname" "$base" "$cow"
 
-        if [ -n "$cow2" ]; then
-          dm_devname_full=$(get_dm_snapshot_name "$base" "$cow" "$cow2")
-          create_dm_snapshot "$dm_devname_full" "/dev/mapper/$dm_devname" "$cow2"
-          dm_devname="$dm_devname_full"
-        fi
+    if [ -n "$cow2" ]; then
+      dm_devname_full=$(get_dm_snapshot_name "$base" "$cow" "$cow2")
+      create_dm_snapshot "$dm_devname_full" "/dev/mapper/$dm_devname" "$cow2"
+      dm_devname="$dm_devname_full"
+    fi
 
-        if [ "$t" == "snapshot" ]; then
-          #that's all for snapshot, store name of prepared device
-          echo "/dev/mapper/$dm_devname"
-        elif [ "$t" == "origin" ]; then
-          # for origin - prepare snapshot-origin device and store its name
-          dm_devname=origin-$(stat -c '%D:%i' "$base")
-          create_dm_snapshot_origin "$dm_devname" "$base"
-          echo "/dev/mapper/$dm_devname"
-        fi
+    if [ "$t" == "origin" ]; then
+      # for origin - prepare snapshot-origin device and store its name
+      dm_devname=origin-$(stat -c '%D:%i' "$base")
+      create_dm_snapshot_origin "$dm_devname" "$base"
+    fi
+    echo "/dev/mapper/$dm_devname"
 
-        release_lock "block"
-        exit 0
-        ;;
-    esac
+    release_lock "block"
+    exit 0
     ;;
   remove|cleanup)
     if [ "$command" = "cleanup" ]; then
@@ -208,91 +210,78 @@ case "$command" in
     else
       t=$(cat "$HOTPLUG_STORE-type" 2>/dev/null || echo 'MISSING')
     fi
-    case "$t" in
-      snapshot|origin)
-        if [ "$command" = "cleanup" ]; then
-          node=$3
-        else
-          node=$(cat "$HOTPLUG_STORE-node" 2> /dev/null)
-        fi
+    if [ "$command" = "cleanup" ]; then
+      node=$3
+    else
+      node=$(cat "$HOTPLUG_STORE-node" 2> /dev/null)
+    fi
 
-        if [ -z "$node" ]; then
-          #fatal "No device node to remove"
-          #Most likely already removed
-          exit 0
-        fi
+    if [ -z "$node" ]; then
+      #fatal "No device node to remove"
+      #Most likely already removed
+      exit 0
+    fi
 
-        if [ ! -e "$node" ]; then
-          fatal "Device $node does not exists"
-        fi
+    claim_lock "block"
 
-        claim_lock "block"
+    if [ ! -e "$node" ]; then
+      fatal "Device $node does not exist"
+    elif ! is_unused "$node"; then
+      in_use "$1"
+    fi
 
-        use_count=$(dmsetup info "$node" 2>/dev/null|grep Open|awk '{print $3}')
+    unset is_origin origin snapshot deps
 
-        if [ -z "$use_count" ]; then
-            log info "Device $node already removed"
-            release_lock "block"
-            exit 0
-        fi
+    # get list of used (loop) devices
+    deps=$(deps "$node")
 
+    case $node in
+      (/dev/mapper/snapshot-*)
         # do not remove snapshot if snapshot origin is still present
-        if [ "${node/snapshot/}" != "$node" ] && [ -e "/dev/mapper/origin-$(echo "$node"|cut -d- -f2)" ]; then
-          use_count=1
-        fi
-
-        if [ "$use_count" -gt 0 ]; then
-          log info "Device $node still in use - not removing"
-          release_lock "block"
-          exit 0
-        fi
-
-        # get list of used (loop) devices
-        deps="$(dmsetup deps "$node" -o blkdevname | cut -d: -f2 | sed -e 's#(\([a-z0-9-]\+\))#/dev/\1#g')"
-
-        # if this is origin
-        if [ "${node/origin/}" != "$node" ]; then
-          # remove unused snapshots
-          for snap in /dev/mapper/snapshot-$(echo "$node"|cut -d- -f2)-*; do
-            use_count=$(dmsetup info "$snap"|grep Open|awk '{print $3}')
-            if [ "$use_count" -eq 0 ]; then
-              # unused snapshot - remove it
-              deps="$deps $(dmsetup deps "$snap" -o blkdevname | cut -d: -f2 |\
-                   sed -e 's#(\([a-z0-9-]\+\))#/dev/\1#g')"
-              log debug "Removing $snap"
-              dmsetup remove "$snap"
-            fi
-          done
-        fi
-
-        if [ -e "$node" ]; then
-          log debug "Removing $node"
-          dmsetup remove "$node"
-        fi
-
-        # try to free unused devices
-        for dev in $deps; do
-          if [ -b "$dev" ]; then
-            log debug "Removing $dev"
-            case $dev in
-              /dev/loop*)
-                losetup -d "$dev" 2> /dev/null || true
-                ;;
-              /dev/dm-*)
-                dmsetup remove "$dev" 2> /dev/null || true
-                ;;
-            esac
+        if [ -e "${node/snapshot/origin}" ]; then in_use "$1"; fi
+        ;;
+      (/dev/mapper/origin-*)
+        # remove unused snapshots
+        for snap in /dev/mapper/snapshot-$(echo "$node"|cut -d- -f2)-*; do
+          if is_unused "$snap"; then
+            # unused snapshot - remove it
+            deps+=" $(deps "$snap")"
+            log debug "Removing $snap"
+            dmsetup -- remove "$snap"
           fi
         done
-
-        if [ -n "$HOTPLUG_STORE" ]; then
-          rm "$HOTPLUG_STORE-"*
-        fi
-        release_lock "block"
-
-        exit 0
+        ;;
+      (*)
+        fatal "Bad name $node"
         ;;
     esac
+
+    if [ -e "$node" ]; then
+      log debug "Removing $node"
+      dmsetup -- remove "$node"
+    fi
+
+    # try to free unused devices
+    for dev in $deps; do
+      if [ -b "$dev" ]; then
+        log debug "Removing $dev"
+        case $dev in
+          /dev/loop*)
+            losetup -d "$dev" 2> /dev/null || true
+            ;;
+          /dev/dm-*)
+            dmsetup remove "$dev" 2> /dev/null || true
+            ;;
+        esac
+      fi
+    done
+
+    if [ -n "$HOTPLUG_STORE" ]; then
+      rm "$HOTPLUG_STORE-"*
+    fi
+    release_lock "block"
+
+    exit 0
     ;;
 esac
 
