Fix the file pool
This fixes the remaining testsuite issues.  This commit should probably
be rebased away before merging.

diff --git a/linux/system-config/create-snapshot b/linux/system-config/create-snapshot
--- a/linux/system-config/create-snapshot
+++ b/linux/system-config/create-snapshot
@@ -52,17 +52,13 @@ create_dm_snapshot() {
 
   if [ ! -e "/dev/mapper/$dm_devname" ]; then
     # prepare new snapshot device
-    base_dev=$(get_dev "$base")
-    cow_dev=$(get_dev "$cow")
+    base_dev=$(get_dev "$base") || fatal "could not get loop device for $base"
+    cow_dev=$(get_dev "$cow") || fatal "could not get loop device for $cow"
     base_sz=$(blockdev --getsz "$base_dev")
     3< "$base_dev" 4< "$cow_dev" dmsetup create "$dm_devname" \
       --table "0 $base_sz snapshot /dev/fd/3 /dev/fd/4 P $SNAPSHOT_CHUNKSIZE" ||
       fatal 'could not create snapshot'
   fi
-}
-
-deps () {
-  dmsetup -o blkdevname -- deps "$1" | cut -d: -f2 | sed -e 's#(\([a-z0-9-]\+\))#/dev/\1#g'
 }
 
 create_dm_snapshot_origin() {
diff --git a/linux/system-config/destroy-snapshot b/linux/system-config/destroy-snapshot
--- a/linux/system-config/destroy-snapshot
+++ b/linux/system-config/destroy-snapshot
@@ -2,9 +2,14 @@
 
 set -euo pipefail
 shopt -s nullglob
+unset is_origin origin snapshot deps node
 
 is_unused () {
   dmsetup -- info "$1" 2>/dev/null|grep -Eq '^Open count: +0$'
+}
+
+deps () {
+  dmsetup -o blkdevname -- deps "$1" | cut -d: -f2 | sed -e 's#(\([a-z0-9-]\+\))#/dev/\1#g'
 }
 
 fatal () {
@@ -12,13 +17,16 @@ fatal () {
   exit 1
 }
 
-if [ ! -e "$node" ]; then
-  fatal "Device $node does not exist"
-elif ! is_unused "$node"; then
+if [[ "$#" -ne 1 ]]; then
+  fatal "Expected one argument (name of device to remove), got $#"
+elif [[ ! -b "$1" ]]; then
+  fatal "Device $1 does not exist"
+elif ! is_unused "$1"; then
+  echo "Cannot remove device $1 that is still in use!" >&2
   exit 0
 fi
 
-unset is_origin origin snapshot deps
+node=$1
 
 # get list of used (loop) devices
 deps=$(deps "$node")
